// CodeGear C++Builder
// Copyright (c) 1995, 2021 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'GLScene_DT.dpk' rev: 34.00 (Windows)

#ifndef Glscene_dtHPP
#define Glscene_dtHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>	// (rtl)
#include <SysInit.hpp>
#include <FRFaceEditor.hpp>
#include <FRMaterialPreview.hpp>
#include <FRColorEditor.hpp>
#include <FRTextureEdit.hpp>
#include <FRTrackBarEdit.hpp>
#include <FLibMaterialPicker.hpp>
#include <FMaterialEditorForm.hpp>
#include <FGuiLayoutEditor.hpp>
#include <FGuiSkinEditor.hpp>
#include <FShaderMemo.hpp>
#include <FShaderUniformEditor.hpp>
#include <FVectorEditor.hpp>
#include <FSceneEditor.hpp>
#include <FPlugInManagerEditor.hpp>
#include <FXCollectionEditor.hpp>
#include <FInfo.hpp>
#include <GLSceneFormDesign.hpp>
#include <GLXCollectionRegister.hpp>
#include <GLSceneRegister.hpp>
#include <System.UITypes.hpp>	// (rtl)
#include <Winapi.Windows.hpp>	// (rtl)
#include <Winapi.PsAPI.hpp>	// (rtl)
#include <System.Character.hpp>	// (rtl)
#include <System.Internal.ExcUtils.hpp>	// (rtl)
#include <System.SysUtils.hpp>	// (rtl)
#include <System.VarUtils.hpp>	// (rtl)
#include <System.Variants.hpp>	// (rtl)
#include <System.Math.hpp>	// (rtl)
#include <System.Rtti.hpp>	// (rtl)
#include <System.TypInfo.hpp>	// (rtl)
#include <System.Generics.Defaults.hpp>	// (rtl)
#include <System.TimeSpan.hpp>	// (rtl)
#include <System.Classes.hpp>	// (rtl)
#include <System.Messaging.hpp>	// (rtl)
#include <System.Actions.hpp>	// (rtl)
#include <System.DateUtils.hpp>	// (rtl)
#include <System.IOUtils.hpp>	// (rtl)
#include <System.IniFiles.hpp>	// (rtl)
#include <System.Win.Registry.hpp>	// (rtl)
#include <System.UIConsts.hpp>	// (rtl)
#include <Vcl.Graphics.hpp>	// (vcl)
#include <System.SyncObjs.hpp>	// (rtl)
#include <Winapi.UxTheme.hpp>	// (rtl)
#include <Vcl.ActnList.hpp>	// (vcl)
#include <System.AnsiStrings.hpp>	// (rtl)
#include <System.Win.ComObj.hpp>	// (rtl)
#include <Winapi.MsCTF.hpp>	// (rtl)
#include <Vcl.GraphUtil.hpp>	// (vcl)
#include <Winapi.ShellAPI.hpp>	// (rtl)
#include <Vcl.Controls.hpp>	// (vcl)
#include <Vcl.StdCtrls.hpp>	// (vcl)
#include <Vcl.Printers.hpp>	// (vcl)
#include <Vcl.Clipbrd.hpp>	// (vcl)
#include <Vcl.ComCtrls.hpp>	// (vcl)
#include <System.HelpIntfs.hpp>	// (rtl)
#include <Vcl.Dialogs.hpp>	// (vcl)
#include <Vcl.ExtCtrls.hpp>	// (vcl)
#include <Vcl.Themes.hpp>	// (vcl)
#include <Vcl.Menus.hpp>	// (vcl)
#include <Winapi.FlatSB.hpp>	// (rtl)
#include <Vcl.Forms.hpp>	// (vcl)
#include <GLVectorGeometry.hpp>	// (GLScene_RT)
#include <GLCrossPlatform.hpp>	// (GLScene_RT)
#include <GLSLog.hpp>	// (GLScene_RT)
#include <GLPersistentClasses.hpp>	// (GLScene_RT)
#include <GLColor.hpp>	// (GLScene_RT)
#include <Vcl.Imaging.jpeg.hpp>	// (vclimg)
#include <Vcl.Imaging.pngimage.hpp>	// (vclimg)
#include <GR32_System.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_Bindings.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_LowLevel.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_Blend.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_Filters.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_Rasterizers.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_Transforms.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_Resamplers.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_XPThemes.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_MicroTiles.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_Image.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_Backends_Generic.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32_Backends_VCL.hpp>	// (GR32_DSGN_RS10_4)
#include <GR32.hpp>	// (GR32_DSGN_RS10_4)
#include <OpenGLAdapter.hpp>	// (GLScene_RT)
#include <XOpenGL.hpp>	// (GLScene_RT)
#include <GLContext.hpp>	// (GLScene_RT)
#include <Vcl.Buttons.hpp>	// (vcl)
#include <Vcl.ExtDlgs.hpp>	// (vcl)
#include <GLGraphics.hpp>	// (GLScene_RT)
#include <GLCoordinates.hpp>	// (GLScene_RT)
#include <GLXCollection.hpp>	// (GLScene_RT)
#include <GLVectorLists.hpp>	// (GLScene_RT)
#include <GLMaterial.hpp>	// (GLScene_RT)
#include <GLScene.hpp>	// (GLScene_RT)
#include <GLTexture.hpp>	// (GLScene_RT)
#include <GLObjects.hpp>	// (GLScene_RT)
#include <GLBitmapFont.hpp>	// (GLScene_RT)
#include <GLHUDObjects.hpp>	// (GLScene_RT)
#include <GLWin32Context.hpp>	// (GLScene_RT)
#include <GLWin32Viewer.hpp>	// (GLScene_RT)
#include <Winapi.OpenGL.hpp>	// (rtl)
#include <GLTeapot.hpp>	// (GLScene_RT)
#include <GLGeomObjects.hpp>	// (GLScene_RT)
#include <GLProcTextures.hpp>	// (GLScene_RT)
#include <GLTextureImageEditors.hpp>	// (GLScene_RT)
#include <Vcl.Grids.hpp>	// (vcl)
#include <GLWindowsFont.hpp>	// (GLScene_RT)
#include <GLWindows.hpp>	// (GLScene_RT)
#include <GLSMemo.hpp>	// (GLScene_RT)
#include <GLSLParameter.hpp>	// (GLScene_RT)
#include <IDEMessages.hpp>	// (designide)
#include <Vcl.CaptionedDockTree.hpp>	// (vcl)
#include <Vcl.DockTabSet.hpp>	// (vcl)
#include <Vcl.CategoryButtons.hpp>	// (vcl)
#include <Vcl.ButtonGroup.hpp>	// (vcl)
#include <Vcl.SysStyles.hpp>	// (vcl)
#include <Winapi.D2D1.hpp>	// (rtl)
#include <Vcl.Direct2D.hpp>	// (vcl)
#include <Vcl.Styles.hpp>	// (vcl)
#include <BrandingAPI.hpp>	// (designide)
#include <Winapi.GDIPOBJ.hpp>	// (rtl)
#include <PercentageDockTree.hpp>	// (designide)
#include <Winapi.Mapi.hpp>	// (rtl)
#include <Vcl.ExtActns.hpp>	// (vcl)
#include <Vcl.ActnMenus.hpp>	// (vclactnband)
#include <Vcl.ActnMan.hpp>	// (vclactnband)
#include <Vcl.PlatformDefaultStyleActnCtrls.hpp>	// (vclactnband)
#include <BaseDock.hpp>	// (designide)
#include <DeskUtil.hpp>	// (designide)
#include <Vcl.ImageCollection.hpp>	// (vclwinx)
#include <Vcl.WinXCtrls.hpp>	// (vclwinx)
#include <DeskForm.hpp>	// (designide)
#include <DockForm.hpp>	// (designide)
#include <Xml.Win.msxmldom.hpp>	// (xmlrtl)
#include <Xml.xmldom.hpp>	// (xmlrtl)
#include <ToolsAPI.hpp>	// (designide)
#include <Proxies.hpp>	// (designide)
#include <DesignEditors.hpp>	// (designide)
#include <System.Devices.hpp>	// (rtl)
#include <Vcl.AxCtrls.hpp>	// (vcl)
#include <Vcl.AppEvnts.hpp>	// (vcl)
#include <TreeIntf.hpp>	// (designide)
#include <TopLevels.hpp>	// (designide)
#include <StFilSys.hpp>	// (designide)
#include <IDEHelp.hpp>	// (designide)
#include <ComponentDesigner.hpp>	// (designide)
#include <VCLEditors.hpp>	// (designide)
#include <GLObjectManager.hpp>	// (GLScene_RT)
#include <GLAnimatedSprite.hpp>	// (GLScene_RT)
#include <GLCadencer.hpp>	// (GLScene_RT)
#include <GLCustomShader.hpp>	// (GLScene_RT)
#include <GLAsmShader.hpp>	// (GLScene_RT)
#include <GLHeightData.hpp>	// (GLScene_RT)
#include <GLAsyncHDS.hpp>	// (GLScene_RT)
#include <GLAsyncTimer.hpp>	// (GLScene_RT)
#include <GLAtmosphere.hpp>	// (GLScene_RT)
#include <GLBlur.hpp>	// (GLScene_RT)
#include <GLBumpmapHDS.hpp>	// (GLScene_RT)
#include <GLScreen.hpp>	// (GLScene_RT)
#include <GLSmoothNavigator.hpp>	// (GLScene_RT)
#include <GLMesh.hpp>	// (GLScene_RT)
#include <GLMeshUtils.hpp>	// (GLScene_RT)
#include <GLVectorFileObjects.hpp>	// (GLScene_RT)
#include <GLManager.hpp>	// (GLScene_RT)
#include <GLCollision.hpp>	// (GLScene_RT)
#include <GLCompositeImage.hpp>	// (GLScene_RT)
#include <GLConsole.hpp>	// (GLScene_RT)
#include <GLEllipseCollision.hpp>	// (GLScene_RT)
#include <GLMultiPolygon.hpp>	// (GLScene_RT)
#include <GLSpaceText.hpp>	// (GLScene_RT)
#include <GLIsolines.hpp>	// (GLScene_RT)
#include <GLROAMPatch.hpp>	// (GLScene_RT)
#include <GLTerrainRenderer.hpp>	// (GLScene_RT)
#include <GLProxyObjects.hpp>	// (GLScene_RT)
#include <GLMultiProxy.hpp>	// (GLScene_RT)
#include <GLDCE.hpp>	// (GLScene_RT)
#include <GLDynamicTexture.hpp>	// (GLScene_RT)
#include <GLParticleFX.hpp>	// (GLScene_RT)
#include <GLExplosionFx.hpp>	// (GLScene_RT)
#include <GLExtrusion.hpp>	// (GLScene_RT)
#include <GLMultisampleImage.hpp>	// (GLScene_RT)
#include <GLFBORenderer.hpp>	// (GLScene_RT)
#include <GLFeedback.hpp>	// (GLScene_RT)
#include <GLFireFX.hpp>	// (GLScene_RT)
#include <GLFPSMovement.hpp>	// (GLScene_RT)
#include <OpenGL1x.hpp>	// (GLScene_RT)
#include <GLGameMenu.hpp>	// (GLScene_RT)
#include <GLGraph.hpp>	// (GLScene_RT)
#include <GLHeightTileFileHDS.hpp>	// (GLScene_RT)
#include <GLImposter.hpp>	// (GLScene_RT)
#include <GLLensFlare.hpp>	// (GLScene_RT)
#include <GLLinePFX.hpp>	// (GLScene_RT)
#include <GLTextureCombiners.hpp>	// (GLScene_RT)
#include <GLMaterialEx.hpp>	// (GLScene_RT)
#include <GLMaterialMultiProxy.hpp>	// (GLScene_RT)
#include <GLMirror.hpp>	// (GLScene_RT)
#include <GLParticles.hpp>	// (GLScene_RT)
#include <GLPerlin.hpp>	// (GLScene_RT)
#include <GLPerlinPFX.hpp>	// (GLScene_RT)
#include <GLPhongShader.hpp>	// (GLScene_RT)
#include <GLPolyhedron.hpp>	// (GLScene_RT)
#include <GLPortal.hpp>	// (GLScene_RT)
#include <GLPostEffects.hpp>	// (GLScene_RT)
#include <GLProjectedTextures.hpp>	// (GLScene_RT)
#include <GLSArchiveManager.hpp>	// (GLScene_RT)
#include <GLScriptBase.hpp>	// (GLScene_RT)
#include <GLShaderCombiner.hpp>	// (GLScene_RT)
#include <GLShadowHDS.hpp>	// (GLScene_RT)
#include <GLShadowPlane.hpp>	// (GLScene_RT)
#include <GLShadowVolume.hpp>	// (GLScene_RT)
#include <GLSceneForm.hpp>	// (GLScene_RT)
#include <GLSkyBox.hpp>	// (GLScene_RT)
#include <GLSkydome.hpp>	// (GLScene_RT)
#include <GLSLanguage.hpp>	// (GLScene_RT)
#include <GLSLShader.hpp>	// (GLScene_RT)
#include <GLSLBumpShader.hpp>	// (GLScene_RT)
#include <GLSLDiffuseSpecularShader.hpp>	// (GLScene_RT)
#include <GLSLProjectedTextures.hpp>	// (GLScene_RT)
#include <GLTexLensFlare.hpp>	// (GLScene_RT)
#include <GLTexturedHDS.hpp>	// (GLScene_RT)
#include <GLTextureSharingShader.hpp>	// (GLScene_RT)
#include <GLThorFX.hpp>	// (GLScene_RT)
#include <GLTilePlane.hpp>	// (GLScene_RT)
#include <GLTrail.hpp>	// (GLScene_RT)
#include <GLTree.hpp>	// (GLScene_RT)
#include <GLFileTIN.hpp>	// (GLScene_RT)
#include <GLWaterPlane.hpp>	// (GLScene_RT)
#include <GLzBuffer.hpp>	// (GLScene_RT)
#include <GLFileDDS.hpp>	// (GLScene_RT)
#include <DDSImage.hpp>	// (GLScene_RT)
#include <GLFileTGA.hpp>	// (GLScene_RT)
#include <GLFile3DSSceneObjects.hpp>	// (GLScene_RT)
#include <GLFile3DS.hpp>	// (GLScene_RT)
#include <GLFileASE.hpp>	// (GLScene_RT)
#include <GLFileB3D.hpp>	// (GLScene_RT)
#include <GLFileGL2.hpp>	// (GLScene_RT)
#include <GLFileGTS.hpp>	// (GLScene_RT)
#include <GLFileLMTS.hpp>	// (GLScene_RT)
#include <LWObjects.hpp>	// (GLScene_RT)
#include <GLFileLWO.hpp>	// (GLScene_RT)
#include <GLFileMD2.hpp>	// (GLScene_RT)
#include <GLFileMD3.hpp>	// (GLScene_RT)
#include <GLFileMD5.hpp>	// (GLScene_RT)
#include <GLFileMDC.hpp>	// (GLScene_RT)
#include <GLFileMS3D.hpp>	// (GLScene_RT)
#include <GLFileNMF.hpp>	// (GLScene_RT)
#include <GLFileNurbs.hpp>	// (GLScene_RT)
#include <GLFileOBJ.hpp>	// (GLScene_RT)
#include <GLFileOCT.hpp>	// (GLScene_RT)
#include <GLFilePLY.hpp>	// (GLScene_RT)
#include <GLBSP.hpp>	// (GLScene_RT)
#include <GLFileQ3BSP.hpp>	// (GLScene_RT)
#include <GLFileSMD.hpp>	// (GLScene_RT)
#include <GLFileSTL.hpp>	// (GLScene_RT)
#include <GLFileVRML.hpp>	// (GLScene_RT)
#include <GLSoundFileObjects.hpp>	// (GLScene_RT)
#include <GLFileWAV.hpp>	// (GLScene_RT)
#include <GLFileMP3.hpp>	// (GLScene_RT)
#include <GLFileO3TC.hpp>	// (GLScene_RT)
#include <GLFileHDR.hpp>	// (GLScene_RT)
#include <GLFileJPEG.hpp>	// (GLScene_RT)
#include <GLFilePNG.hpp>	// (GLScene_RT)
#include <GLFileBMP.hpp>	// (GLScene_RT)
#include <FileTGA.hpp>	// (GLScene_RT)
#include <GLSound.hpp>	// (GLScene_RT)
#include <GLJoystick.hpp>	// (GLScene_RT)
#include <GLScreenSaver.hpp>	// (GLScene_RT)
#include <GLFullScreenViewer.hpp>	// (GLScene_RT)
#include <GLBehaviours.hpp>	// (GLScene_RT)
// PRG_EXT: .bpl
// BPI_DIR: ..\..\lib\Win32
// OBJ_DIR: ..\..\lib\Win32
// OBJ_EXT: .obj

//-- user supplied -----------------------------------------------------------

namespace Glscene_dt
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
}	/* namespace Glscene_dt */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_GLSCENE_DT)
using namespace Glscene_dt;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Glscene_dtHPP
