program SkiaDemo;

uses
  System.StartUpCopy,
  FMX.Forms,
  frmMain in 'frmMain.pas' {Form2},
  Mf6.AdvFileReaderUnit in '..\..\MF6InputReader\Mf6.AdvFileReaderUnit.pas',
  Mf6.AtsFileReaderUnit in '..\..\MF6InputReader\Mf6.AtsFileReaderUnit.pas',
  Mf6.BuyFileReaderUnit in '..\..\MF6InputReader\Mf6.BuyFileReaderUnit.pas',
  Mf6.ChdFileReaderUnit in '..\..\MF6InputReader\Mf6.ChdFileReaderUnit.pas',
  Mf6.CncFileReaderUnit in '..\..\MF6InputReader\Mf6.CncFileReaderUnit.pas',
  Mf6.CrossSectionFileReaderUnit in '..\..\MF6InputReader\Mf6.CrossSectionFileReaderUnit.pas',
  Mf6.CSubFileReaderUnit in '..\..\MF6InputReader\Mf6.CSubFileReaderUnit.pas',
  Mf6.CustomMf6PersistentUnit in '..\..\MF6InputReader\Mf6.CustomMf6PersistentUnit.pas',
  Mf6.DisFileReaderUnit in '..\..\MF6InputReader\Mf6.DisFileReaderUnit.pas',
  Mf6.DisuFileReaderUnit in '..\..\MF6InputReader\Mf6.DisuFileReaderUnit.pas',
  Mf6.DisvFileReaderUnit in '..\..\MF6InputReader\Mf6.DisvFileReaderUnit.pas',
  Mf6.DrnFileReaderUnit in '..\..\MF6InputReader\Mf6.DrnFileReaderUnit.pas',
  Mf6.DspFileReaderUnit in '..\..\MF6InputReader\Mf6.DspFileReaderUnit.pas',
  Mf6.EvtFileReaderUnit in '..\..\MF6InputReader\Mf6.EvtFileReaderUnit.pas',
  Mf6.ExchangeFileReaderUnit in '..\..\MF6InputReader\Mf6.ExchangeFileReaderUnit.pas',
  Mf6.FmiFileReaderUnit in '..\..\MF6InputReader\Mf6.FmiFileReaderUnit.pas',
  Mf6.GhbFileReaderUnit in '..\..\MF6InputReader\Mf6.GhbFileReaderUnit.pas',
  Mf6.GncFileReaderUnit in '..\..\MF6InputReader\Mf6.GncFileReaderUnit.pas',
  Mf6.HfbFileReaderUnit in '..\..\MF6InputReader\Mf6.HfbFileReaderUnit.pas',
  Mf6.IcFileReaderUnit in '..\..\MF6InputReader\Mf6.IcFileReaderUnit.pas',
  Mf6.ImsFileReaderUnit in '..\..\MF6InputReader\Mf6.ImsFileReaderUnit.pas',
  Mf6.IstFileReaderUnit in '..\..\MF6InputReader\Mf6.IstFileReaderUnit.pas',
  Mf6.LakeTableFileReaderUnit in '..\..\MF6InputReader\Mf6.LakeTableFileReaderUnit.pas',
  Mf6.LakFileReaderUnit in '..\..\MF6InputReader\Mf6.LakFileReaderUnit.pas',
  Mf6.LktFileReaderUnit in '..\..\MF6InputReader\Mf6.LktFileReaderUnit.pas',
  Mf6.MawFileReaderUnit in '..\..\MF6InputReader\Mf6.MawFileReaderUnit.pas',
  Mf6.MstFileReaderUnit in '..\..\MF6InputReader\Mf6.MstFileReaderUnit.pas',
  Mf6.MvrFileReaderUnit in '..\..\MF6InputReader\Mf6.MvrFileReaderUnit.pas',
  Mf6.MvtFileReaderUnit in '..\..\MF6InputReader\Mf6.MvtFileReaderUnit.pas',
  Mf6.MwtFileReaderUnit in '..\..\MF6InputReader\Mf6.MwtFileReaderUnit.pas',
  Mf6.NameFileReaderUnit in '..\..\MF6InputReader\Mf6.NameFileReaderUnit.pas',
  Mf6.NpfFileReaderUnit in '..\..\MF6InputReader\Mf6.NpfFileReaderUnit.pas',
  Mf6.ObsFileReaderUnit in '..\..\MF6InputReader\Mf6.ObsFileReaderUnit.pas',
  Mf6.OcFileReaderUnit in '..\..\MF6InputReader\Mf6.OcFileReaderUnit.pas',
  Mf6.RchFileReaderUnit in '..\..\MF6InputReader\Mf6.RchFileReaderUnit.pas',
  Mf6.RivFileReaderUnit in '..\..\MF6InputReader\Mf6.RivFileReaderUnit.pas',
  Mf6.SfrFileReaderUnit in '..\..\MF6InputReader\Mf6.SfrFileReaderUnit.pas',
  Mf6.SftFileReaderUnit in '..\..\MF6InputReader\Mf6.SftFileReaderUnit.pas',
  Mf6.SimulationNameFileReaderUnit in '..\..\MF6InputReader\Mf6.SimulationNameFileReaderUnit.pas',
  Mf6.SpcFileReaderUnit in '..\..\MF6InputReader\Mf6.SpcFileReaderUnit.pas',
  Mf6.SrcFileReaderUnit in '..\..\MF6InputReader\Mf6.SrcFileReaderUnit.pas',
  Mf6.SsmFileReaderUnit in '..\..\MF6InputReader\Mf6.SsmFileReaderUnit.pas',
  Mf6.StoFileReaderUnit in '..\..\MF6InputReader\Mf6.StoFileReaderUnit.pas',
  Mf6.TDisFileReaderUnit in '..\..\MF6InputReader\Mf6.TDisFileReaderUnit.pas',
  Mf6.TimeArraySeriesFileReaderUnit in '..\..\MF6InputReader\Mf6.TimeArraySeriesFileReaderUnit.pas',
  Mf6.TimeSeriesFileReaderUnit in '..\..\MF6InputReader\Mf6.TimeSeriesFileReaderUnit.pas',
  Mf6.TvkFileReaderUnit in '..\..\MF6InputReader\Mf6.TvkFileReaderUnit.pas',
  Mf6.TvsFileReaderUnit in '..\..\MF6InputReader\Mf6.TvsFileReaderUnit.pas',
  Mf6.UzfFileReaderUnit in '..\..\MF6InputReader\Mf6.UzfFileReaderUnit.pas',
  Mf6.UztFileReaderUnit in '..\..\MF6InputReader\Mf6.UztFileReaderUnit.pas',
  Mf6.VscFileReaderUnit in '..\..\MF6InputReader\Mf6.VscFileReaderUnit.pas',
  Mf6.WelFileReaderUnit in '..\..\MF6InputReader\Mf6.WelFileReaderUnit.pas',
  ModelMuseUtilities in '..\..\ModelMuse\ModelMuseUtilities.pas',
  ReadModflowArrayUnit in '..\..\ModelMuse\ReadModflowArrayUnit.pas',
  FastGEO in '..\..\ModelMuse\FastGEO.pas',
  GoPhastTypes in '..\..\ModelMuse\GoPhastTypes.pas',
  ColorSchemes in '..\..\ModelMuse\ColorSchemes.pas',
  ColorSchemesInterface in '..\..\ModelMuse\ColorSchemesInterface.pas',
  DrawFrameUnit in 'DrawFrameUnit.pas' {DrawFrame: TFrame},
  FreeThread in 'FreeThread.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TForm2, Form2);
  Application.Run;
end.
