# ETS: Evapotranspiration Segments package file created on 12/12/2015 by ModelMuse version 3.6.3.5.
# ETS input file for ets1 and etsdrt test cases
     1     9     1     2 # DataSet 1: NETSOP IEVTCB, NPETS, NETSEG
ETS_Max ETS  9.999999800000E-003      1 # Data Set 2: PARNAM PARTYP Parval NCLU
R_Mult_1 ALL
     1     1     1    -1     1 # Data Set 4: INETSS INETSR INETSX [INIETS [INSGDF]] Stress period 1
CONSTANT     1.000000000000E+002  # Data Set 5: ETSS
ETS_Max 12 # Data Set 7: PARNAM IETSPF
CONSTANT     3.600000000000E+001  # Data Set 8: ETSX
CONSTANT     5.000000000000E-001  # Data Set 10: PXDP
CONSTANT     1.000000000000E-001  # Data Set 11: PETM
