@echo off
REM
REM   Run composite transient Modflow model
REM   with input files in current directory
REM

Echo Model.bat is making a composite transient model run...

REM   Distribute/interpolate K values estimated at pilot points
Echo Model.bat is invoking fac2r.bat...
call fac2r.bat

REM   Copy the array files generated by fac2r.bat to the model directory
REM  echo.
REM  Echo Model.bat is invoking copy_work.bat...
REM  call copy_work.bat

REM   CD to the model directory and run the model
echo.
Echo Model.bat is invoking run_tr.bat...
call run_tr.bat

echo.
echo Model.bat is done.
