object frmTree: TfrmTree
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'frmTree'
  ClientHeight = 254
  ClientWidth = 488
  Color = clSkyBlue
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -10
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesigned
  OnHide = FormHide
  OnMouseDown = FormMouseDown
  PixelsPerInch = 96
  TextHeight = 12
end
