object frmCustomGoPhast: TfrmCustomGoPhast
  Left = 550
  Top = 496
  Caption = 'frmCustomGoPhast'
  ClientHeight = 234
  ClientWidth = 426
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -16
  Font.Name = 'Arial'
  Font.Pitch = fpVariable
  Font.Style = []
  PopupMode = pmAuto
  Position = poMainFormCenter
  Scaled = False
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnHide = FormHide
  OnHelp = FormHelp
  OnShow = FormShow
  TextHeight = 18
end
