unit InterpolatedObsResourceUnit;

interface

const
  StrBEGINFILEOPTIONS = 'BEGIN FILE_OPTIONS';
  StrENDFILEOPTIONS = 'END FILE_OPTIONS';
  StrOUTPUTFILE = 'OUTPUT_FILE';
  StrSWIOBSFILE = 'SWI_OBS_FILE';
  StrSWIOBSFORMAT = 'SWI_OBS_FORMAT';
  StrBINARY = 'BINARY';
  StrSINGLE = 'SINGLE';
  StrDOUBLE = 'DOUBLE';
  StrASCII = 'ASCII';
  StrTOTALNUMBEROFOBSE = 'TOTAL_NUMBER_OF_OBSERVATIONS';
  StrNUMBEROFZETASURFA = 'NUMBER_OF_ZETA_SURFACES';

  StrBEGINOBSERVATIONS = 'BEGIN OBSERVATIONS';
  StrENDOBSERVATIONS = 'END OBSERVATIONS';
  StrBEGINOBSERVATION = 'BEGIN_OBSERVATION';
  StrENDOBSERVATION = 'END_OBSERVATION';
  StrZetaNAME = 'NAME';
  StrZetaTIME = 'TIME';
  StrZETASURFACENUMBER = 'ZETA_SURFACE_NUMBER';
  StrOBSERVEDVALUE = 'OBSERVED_VALUE';
  StrSWIOBSERVATION = 'SWI_OBSERVATION';

implementation

end.
