jtf @
#UCODE Template File
   45
VANI_QPlat @VANI_QPlat    @
VANI_Qbas  @VANI_Qbas     @
VANI_BR    @VANI_BR       @
Sy_Qal     @Sy_Qal        @
Sy_TDW     @Sy_TDW        @
Sy_TKD     @Sy_TKD        @
Sy_KA      @Sy_KA         @
Sy_KLF     @Sy_KLF        @
SS_coarse  @SS_coarse     @
SS_fine    @SS_fine       @
ET_max     @ET_max        @
DRN_COND   @DRN_COND      @
BarrLake   @BarrLake      @
MiltonRes  @MiltonRes     @
CherryCkRs @CherryCkRs    @
Chatfield  @Chatfield     @
AuroraRes  @AuroraRes     @
GHB_BS_CK  @GHB_BS_CK     @
GHB_Nuss   @GHB_Nuss      @
SFR_PLATTE @SFR_PLATTE    @
SFR_TRIBS  @SFR_TRIBS     @
RCH_Qal    @RCH_Qal       @
RCH_Tdw    @RCH_Tdw       @
RCH_TKd    @RCH_TKd       @
RCH_Ka     @RCH_Ka        @
RCH_Klf    @RCH_Klf       @
RCH_Resid  @RCH_Resid     @
RCH_AgIrr  @RCH_AgIrr     @
K_qal      @K_qal         @
K_Q_BigSdy @K_Q_BigSdy    @
K_Q_BlkSql @K_Q_BlkSql    @
K_utdw     @K_utdw        @
K_tdwc     @K_tdwc        @
K_ltdw     @K_ltdw        @
K_tkduc    @K_tkduc       @
K_tkdlc    @K_tkdlc       @
K_kac      @K_kac         @
K_klc      @K_klc         @
FLWG_WELLS @FLWG_WELLS    @
Q_Qal_IR   @Q_Qal_IR      @
Q_Qal_MU   @Q_Qal_MU      @
Q_Qal_CI   @Q_Qal_CI      @
Q_BR_IR    @Q_BR_IR       @
Q_BR_MU    @Q_BR_MU       @
Q_BR_CI    @Q_BR_CI       @
